#!/usr/bin/env bash
BSCHECKSUM=bschecksum
BSDATA=bsdata
BSAPPLY=bsapply
BSINFO=bsinfo


function echoBold() {
    local BOLD="\033[1m"
    local NO_COLOR="\033[0m"
    echo -e ${BOLD}${1}${NO_COLOR}
}

source="$1"
destination="$2"

sourceSum="${source}.sum"
destinationSum="${destination}.sum"

patch="${source}.patch"

echoBold "### Update source checksum ${sourceSum}"
${BSCHECKSUM} --target="${source}" --output="${sourceSum}" || exit 1
echo

if [ ! -e "${destination}" -o ! -e "${destinationSum}" ]; then
    echoBold "### Full copy of ${source}"
    rsync --progress "${source}" "${destination}" || exit 2
    rsync --progress "${sourceSum}" "${destinationSum}" || exit 3
    echo

    echoBold "### Delete source checksum ${sourceSum}"
    rm "${sourceSum}"
    exit 0
fi

echoBold "### Create patch ${patch}"
${BSDATA} --target="${source}" --master="${sourceSum}" --remote="${destinationSum}" --output="${patch}" || exit 4
echo

echoBold "### Apply patch ${patch} to ${destination}"
${BSAPPLY} --target="${destination}" --data="${patch}" || exit 5
echo

echoBold "### Update destination checksum ${destinationSum}"
cp "${sourceSum}" "${destinationSum}"
echo

echoBold "### Delete patch ${patch}"
rm "${patch}"
echo

echoBold "### Delete source checksum ${sourceSum}"
rm "${sourceSum}"
echo

# echoBold "### Checksums"
# md5sum --binary "${source}" "${destination}"

