#!/usr/bin/env bash
BSCHECKSUM=bschecksum
BSDATA=bsdata
BSAPPLY=bsapply
BSINFO=bsinfo

source="$1"
destination="$2"

sourceSum="${source}.sum"
destinationSum="${destination}.sum"

patch="${source}.patch"

echo "### Update source checksum ${sourceSum}"
${BSCHECKSUM} --source="${source}" --output="${sourceSum}" || exit 1
echo

if [ ! -e "${destination}" -o ! -e "${destinationSum}" ]; then
    echo "### Full copy of ${source}"
    rsync --progress "${source}" "${destination}" || exit 2
    rsync --progress "${sourceSum}" "${destinationSum}" || exit 3
    echo

    echo "### Delete source checksum ${sourceSum}"
    rm "${sourceSum}"
    exit 0
fi

echo "### Create patch ${patch}"
${BSDATA} --source="${source}" --master="${sourceSum}" --remote="${destinationSum}" --output="${patch}" || exit 4
echo

echo "### Apply patch ${patch} to ${destination}"
${BSAPPLY} --source="${destination}" --data="${patch}" || exit 5
echo

echo "### Update destination checksum ${destinationSum}"
cp "${sourceSum}" "${destinationSum}"
echo

echo "### Delete patch ${patch}"
rm "${patch}"
echo

echo "### Delete source checksum ${sourceSum}"
rm "${sourceSum}"
echo

# echo "### Checksums"
# md5sum --binary "${source}" "${destination}"

